language: c++
sudo: required
dist: xenial

os:
  - linux
  - osx

compiler:
  - gcc
  - clang
 
env: 
  global:
    - CTEST_OUTPUT_ON_FAILURE=True # Print output of failed unit test.

  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

matrix:
  exclude:
    - os: linux
      compiler: clang
    - os: osx
      compiler: gcc

cache:
  directories:
    - $HOME/downloads
    - /usr/local/opt/qt
    - /opt/qt512
    - $HOME/Library/Caches/Homebrew

addons:
  homebrew:
    packages:
    - qt
    update: true
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    - sourceline: 'ppa:beineri/opt-qt-5.12.3-xenial'
    packages:
    - gcc-6 
    - g++-6
    - qt512tools

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
      sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-6 90
    fi

install:
  - mkdir -p $HOME/downloads  && cd $HOME/downloads

  # Install Qt5.12
  - |
    # Install Qt
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      source /opt/qt512/bin/qt512-env.sh
    else
      export QTDIR="/usr/local/opt/qt"
      export PATH="$QTDIR/bin:$PATH"
    fi

before_script:
  - cd /tmp
  - mkdir build
  - cd build
  - qmake ${TRAVIS_BUILD_DIR}/futures.pro
  - make

script:
  - ./futures
